# Generated by Django 5.2.9 on 2025-12-13 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="next_payment",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
